CREATE DATABASE "FOOTBALL TICKET BOOKING SYSTEM";

-- USERS TABLE
CREATE TABLE USERS (
    USER_ID SERIAL,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    
    -- CONSTRAINTS
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_USERS_ROLE CHECK (ROLE IN ('Ticket Manager', 'Football Fan'))
);

-- MATCHES TABLE
CREATE TABLE MATCHES (
    MATCH_ID SERIAL,
    FIXTURE VARCHAR(150) NOT NULL,
    TOURNAMENT_CATEGORY VARCHAR(100) NOT NULL,
    BASE_TICKET_PRICE DECIMAL(10, 2) NOT NULL,
    MATCH_STATUS VARCHAR(50) NOT NULL,
    
    -- CONSTRAINTS
    CONSTRAINT PK_MATCHES PRIMARY KEY (MATCH_ID),
    CONSTRAINT CHK_MATCHES_PRICE CHECK (BASE_TICKET_PRICE >= 0),
    CONSTRAINT CHK_MATCHES_STATUS CHECK (MATCH_STATUS IN ('Available', 'Selling Fast', 'Sold Out', 'Postponed'))
);

-- BOOKINGS TABLE
CREATE TABLE BOOKINGS (
    BOOKING_ID SERIAL,
    USER_ID INT NOT NULL,
    MATCH_ID INT NOT NULL,
    SEAT_NUMBER VARCHAR(20) NOT NULL,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    TOTAL_COST DECIMAL(10, 2) NOT NULL,
    
    -- CONSTRAINTS
    CONSTRAINT PK_BOOKINGS PRIMARY KEY (BOOKING_ID),
    CONSTRAINT FK_BOOKINGS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKINGS_MATCH FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(match_id) ON DELETE CASCADE,
    CONSTRAINT CHK_BOOKINGS_COST CHECK (TOTAL_COST >= 0),
    CONSTRAINT CHK_BOOKINGS_STATUS CHECK (PAYMENT_STATUS IN ('Pending', 'Confirmed', 'Cancelled', 'Refunded') OR PAYMENT_STATUS IS NULL)
);
